/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package distsys.smartmarine;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
/**
 *
 * @author ilian
 */
public class MarineGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MarineGUI.class.getName());

    /**
     * Creates new form MarineGUI
     */
    public MarineGUI() {
        initComponents();
        txtAreaOutput.setEditable(false);
        txtAreaOutput.setLineWrap(true);
        txtAreaOutput.setWrapStyleWord(true);
        txtAreaOutput.setText("Results will appear here...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTemperature = new javax.swing.JButton();
        btnPH = new javax.swing.JButton();
        btnSpecies = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaOutput = new javax.swing.JTextArea();
        cmbSpecies = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbLocation = new javax.swing.JComboBox<>();
        btnListSpecies = new javax.swing.JButton();
        btnActiveAlerts = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCreateAlert = new javax.swing.JButton();
        cmbAlertType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtAlertMessage = new javax.swing.JTextField();
        cmbSeverity = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTemperature.setText("Get");
        btnTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemperatureActionPerformed(evt);
            }
        });

        btnPH.setText("Get");
        btnPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHActionPerformed(evt);
            }
        });

        btnSpecies.setText("Get");
        btnSpecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeciesActionPerformed(evt);
            }
        });

        jLabel1.setText("Water Temperature");

        jLabel2.setText("Water PH");

        jLabel3.setText("Species Status");

        txtAreaOutput.setEditable(false);
        txtAreaOutput.setColumns(20);
        txtAreaOutput.setRows(5);
        jScrollPane1.setViewportView(txtAreaOutput);

        cmbSpecies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Common Dolphin", "Grey Seal", "Leatherback Turtle" }));

        jLabel4.setText("Species Location");

        cmbLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dublin Bay", "Atlantic Zone" }));

        btnListSpecies.setText("Search");
        btnListSpecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListSpeciesActionPerformed(evt);
            }
        });

        btnActiveAlerts.setText("View");
        btnActiveAlerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiveAlertsActionPerformed(evt);
            }
        });

        jLabel5.setText("Active Alerts");

        jLabel6.setText("Create Alert");

        btnCreateAlert.setText("Create");
        btnCreateAlert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAlertActionPerformed(evt);
            }
        });

        cmbAlertType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POLLUTION", "SPECIES_RISK" }));

        jLabel7.setText("Severity");

        txtAlertMessage.setText("Enter message...");

        cmbSeverity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Water Quality");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Marine Life");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Alerts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(cmbSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnSpecies)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnActiveAlerts)
                                                .addComponent(jLabel5)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(87, 87, 87)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnTemperature)
                                        .addComponent(jLabel1))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(btnListSpecies)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmbSeverity, 0, 1, Short.MAX_VALUE))
                                        .addComponent(jLabel2)
                                        .addComponent(btnPH)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbAlertType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(217, 217, 217)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtAlertMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCreateAlert))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTemperature)
                    .addComponent(btnPH))
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListSpecies)
                    .addComponent(btnSpecies))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActiveAlerts)
                    .addComponent(cmbAlertType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSeverity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAlertMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateAlert)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemperatureActionPerformed
        // TODO add your handling code here:
        ManagedChannel channel = ManagedChannelBuilder
        .forAddress("localhost", 50051)
        .usePlaintext()
        .build();

try {
    WaterQualityServiceGrpc.WaterQualityServiceBlockingStub stub =
            WaterQualityServiceGrpc.newBlockingStub(channel);

    Empty request = Empty.newBuilder().build();
    Temperature response = stub.getWaterTemperature(request);

    txtAreaOutput.setText("Water Temperature: " + response.getValue() + " C");

} catch (Exception e) {
    txtAreaOutput.setText("Error: " + e.getMessage());
} finally {
    channel.shutdown();
}
    }//GEN-LAST:event_btnTemperatureActionPerformed

    private void btnPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHActionPerformed
        // TODO add your handling code here:
        ManagedChannel channel = ManagedChannelBuilder
        .forAddress("localhost", 50051)
        .usePlaintext()
        .build();

try {
    WaterQualityServiceGrpc.WaterQualityServiceBlockingStub stub =
            WaterQualityServiceGrpc.newBlockingStub(channel);

    Empty request = Empty.newBuilder().build();
    PHReading response = stub.getWaterPH(request);

    txtAreaOutput.setText("Water pH: " + response.getValue());

} catch (Exception e) {
    txtAreaOutput.setText("Error: " + e.getMessage());
} finally {
    channel.shutdown();
}
    }//GEN-LAST:event_btnPHActionPerformed

    private void btnSpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeciesActionPerformed
        // TODO add your handling code here:
        ManagedChannel channel = ManagedChannelBuilder
        .forAddress("localhost", 50051)
        .usePlaintext()
        .build();

try {
    MarineLifeServiceGrpc.MarineLifeServiceBlockingStub stub =
            MarineLifeServiceGrpc.newBlockingStub(channel);

    String speciesName = cmbSpecies.getSelectedItem().toString();

    SpeciesRequest request = SpeciesRequest.newBuilder()
            .setName(speciesName)
            .build();

    SpeciesStatus response = stub.getSpeciesStatus(request);

    txtAreaOutput.setText(
            "Species: " + response.getName() + "\n" +
            "Trend: " + response.getPopulationTrend() + "\n" +
            "Last seen: " + response.getLastSeenDaysAgo() + " days ago"
    );

} catch (Exception e) {
    txtAreaOutput.setText("Error: " + e.getMessage());
} finally {
    channel.shutdown();
}
    }//GEN-LAST:event_btnSpeciesActionPerformed

    private void btnListSpeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListSpeciesActionPerformed
        // TODO add your handling code here:
        ManagedChannel channel = ManagedChannelBuilder
        .forAddress("localhost", 50051)
        .usePlaintext()
        .build();

try {
    MarineLifeServiceGrpc.MarineLifeServiceBlockingStub stub =
            MarineLifeServiceGrpc.newBlockingStub(channel);

    int locationId;
    String selectedLocation = cmbLocation.getSelectedItem().toString();

    if (selectedLocation.equals("Dublin Bay")) {
        locationId = 1;
    } else {
        locationId = 2;
    }

    LocationRequest request = LocationRequest.newBuilder()
            .setLocationId(locationId)
            .build();

    java.util.Iterator<Species> responses = stub.listObservedSpecies(request);

    StringBuilder output = new StringBuilder();

    while (responses.hasNext()) {
        Species species = responses.next();

        output.append("Species: ").append(species.getName()).append("\n");
        output.append("Category: ").append(species.getCategory()).append("\n");
        output.append("Risk: ").append(species.getRiskStatus()).append("\n");
        output.append("-------------------------\n");
    }

    txtAreaOutput.setText(output.toString());

} catch (Exception e) {
    txtAreaOutput.setText("Error: " + e.getMessage());
} finally {
    channel.shutdown();
}
    }//GEN-LAST:event_btnListSpeciesActionPerformed

    private void btnActiveAlertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActiveAlertsActionPerformed
        // TODO add your handling code here:
        ManagedChannel channel = ManagedChannelBuilder
        .forAddress("localhost", 50051)
        .usePlaintext()
        .build();

try {
    AlertServiceGrpc.AlertServiceBlockingStub stub =
            AlertServiceGrpc.newBlockingStub(channel);

    Empty request = Empty.newBuilder().build();

    java.util.Iterator<Alert> responses = stub.getActiveAlerts(request);

    StringBuilder output = new StringBuilder();

    while (responses.hasNext()) {
        Alert alert = responses.next();

        output.append("Alert ID: ").append(alert.getAlertId()).append("\n");
        output.append("Type: ").append(alert.getAlertType()).append("\n");
        output.append("Message: ").append(alert.getMessage()).append("\n");
        output.append("Severity: ").append(alert.getSeverity()).append("\n");
        output.append("-------------------------\n");
    }

    txtAreaOutput.setText(output.toString());

} catch (Exception e) {
    txtAreaOutput.setText("Error: " + e.getMessage());
} finally {
    channel.shutdown();
}
    }//GEN-LAST:event_btnActiveAlertsActionPerformed

    private void btnCreateAlertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAlertActionPerformed
        // TODO add your handling code here:
        ManagedChannel channel = ManagedChannelBuilder
        .forAddress("localhost", 50051)
        .usePlaintext()
        .build();

try {
    AlertServiceGrpc.AlertServiceBlockingStub stub =
            AlertServiceGrpc.newBlockingStub(channel);

    String alertType = cmbAlertType.getSelectedItem().toString();
    String message = txtAlertMessage.getText();
    int severity = Integer.parseInt(cmbSeverity.getSelectedItem().toString());

    AlertRequest request = AlertRequest.newBuilder()
            .setSourceService("MarineGUI")
            .setAlertType(alertType)
            .setMessage(message)
            .setSeverity(severity)
            .build();

    AlertResponse response = stub.createAlert(request);

    txtAreaOutput.setText(
            "Alert Created!\n" +
            "ID: " + response.getAlertId() + "\n" +
            "Status: " + response.getCreated()
    );

} catch (Exception e) {
    txtAreaOutput.setText("Error: " + e.getMessage());
} finally {
    channel.shutdown();
}
    }//GEN-LAST:event_btnCreateAlertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MarineGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActiveAlerts;
    private javax.swing.JButton btnCreateAlert;
    private javax.swing.JButton btnListSpecies;
    private javax.swing.JButton btnPH;
    private javax.swing.JButton btnSpecies;
    private javax.swing.JButton btnTemperature;
    private javax.swing.JComboBox<String> cmbAlertType;
    private javax.swing.JComboBox<String> cmbLocation;
    private javax.swing.JComboBox<String> cmbSeverity;
    private javax.swing.JComboBox<String> cmbSpecies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlertMessage;
    private javax.swing.JTextArea txtAreaOutput;
    // End of variables declaration//GEN-END:variables
}
